name: Continuous Integration

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Maven
      uses: apache/maven@v3 
      with:
        maven-version: '3.8.4'  

    - name: Install Dependencies
      run: mvn install

    - name: Build project
      run: mvn clean package

    - name: Run unit tests
      run: mvn test

    - name: Verify script execution
      run: echo "Script executed successfully!"

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -am "CI: Run script"
        git push

    - name: Display Git status
      run: git status
