name: Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: "zulu"

    - name: Show Java version
      run: java -version

    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files
      run: ls -a

    - name: Install Dependencies
      run: ./mvnw compile  # Assuming you're using Maven, adjust if you're using a different build tool

    - name: Build application
      run: ./mvnw package -DskipTests

    - name: Test application
      run: ./mvnw test
